"""updated columns

Revision ID: f2e799911e29
Revises: 
Create Date: 2026-08-28 10:38:09.648303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2e799911e29'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('dietary_tags', sa.String(), nullable=True))
    op.add_column('items', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('items', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'items', 'restaurants', ['restaurant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_column('items', 'restaurant_id')
    op.drop_column('items', 'rating')
    op.drop_column('items', 'dietary_tags')
    # ### end Alembic commands ###
