"""updates

Revision ID: d10ee053b56c
Revises: 
Create Date: 2026-08-27 13:19:39.745860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd10ee053b56c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'items', 'restaurants', ['restaurant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.alter_column('items', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
